---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes

  - name: Uninstall apache and packages
    apt:
      name: apache2
      state: absent
